version: '3'
services:
  cassandra:
    image: cassandra:latest
    ports:
      - "7000:32777"
      - "7001:32776"
      - "7199:32775"
      - "9042:9042"
      - "9160:32773"
    volumes:
      - ./cassandra:/var/lib/cassandra
      - ./cassandra-entrypoint.sh:/docker-entrypoint.sh
      - ./cassandra-commands.cql:/docker-entrypoint-initdb.d/cassandra-commands.cql
  postgres:
    image: postgres:latest
    ports:
      - "5432:32778"
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "4369:32782"
      - "5671:32781"
      - "5672:5672"
      - "25672:32779"
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
